### ISSUE TITLE
Npgsql.NpgsqlConnector.Connect timeout on migration from postgresql 14.1 to 15.3

### ISSUE THREAD

**Issue by nknprasad** [npgsql/EntityFramework6.Npgsql#197] opened 2023-07-20 18:26 UTC
### **Environment:**
Operating System: Windows 10 Enterprise 64-bit (19045.2965)
Application uses .Net Framework 4.7.2
Migrated from PostgreSQL 14.1 to 15.3 and seeing this exception randomly. Not consistent.
Using Ngpsql 5.0.70 & NgpsqlEntityFramework6 (3.1.1.0)

### **Issue:**
An error occurred while getting provider information from the database. This can be caused by Entity Framework using an incorrect connection string. Check the inner exceptions for details and ensure that the connection string is correct. (See inner exception for details.) ---> System.Data.Entity.Core.ProviderIncompatibleException: An error occurred while getting provider information from the database. This can be caused by Entity Framework using an incorrect connection string. Check the inner exceptions for details and ensure that the connection string is correct. ---> System.Data.Entity.Core.ProviderIncompatibleException: The provider did not return a ProviderManifestToken string. ---> _System.TimeoutException: The operation has timed out.
at Npgsql.NpgsqlConnector.Connect(NpgsqlTimeout timeout)
at Npgsql.NpgsqlConnector.d__179.MoveNext()_

**Comment by roji** [comment] 2023-07-20 19:28
Please don't cross-post the same issue in multiple repositories, that just causes noise and consumes time. A single issue is enough, we can always move it around if we need to.

**Comment by roji** [comment] 2023-07-20 19:28
Duplicate of https://github.com/npgsql/npgsql/issues/5168

**Closed as not planned by roji** 2023-07-20 19:28 UTC
