### ISSUE TITLE
VS2019 Unable to create model from database

### ISSUE THREAD

**Issue by Rumpelstinsk** [npgsql/EntityFramework6.Npgsql#140] opened 2019-11-04 11:00 UTC
I'm unable to create an edmx model from a PostgreSQL database. I'm trying to build demo project, so I have created a simple schema on postgres, with only one table:

> CREATE TABLE poc_client_dev.tareas
> (
>     "Id" integer NOT NULL DEFAULT nextval('poc_client_dev."tareas_Id_seq"'::regclass),
>     "Nombre" character varying(255) COLLATE pg_catalog."default" NOT NULL,
>     "Descripcion" character varying(255) COLLATE pg_catalog."default",
>     responsable character varying(255) COLLATE pg_catalog."default",
>     CONSTRAINT tareas_pkey PRIMARY KEY ("Id")
> )

After installing on visual studio the extension Npgsql PostgreSQL Integration and the following nuggets on my project: Npgsql(v.4.1.1), Entityframework (6.3.0) and EntityFramework6.Npgsql (6.3.0), I tried to add an edmx.

Everything seems to works, it's able to connect to the database, and retrieve the schemas:[https://i.stack.imgur.com/kUPlj.png](url)

However, when I click Finish, instead of creating the model, it shows an error and throws an exception on the output window: [https://i.stack.imgur.com/3E2Qe.png](url)

> Unable to generate the model because of the following exception: 'System.Data.Entity.Core.EntityCommandExecutionException: An error occurred while executing the command definition. See the inner exception for details. ---> Npgsql.PostgresException: 42703: no existe la columna ad.adsrc
>    at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
> .... //and goes on the stack trace

The relevant part is this: 

> Npgsql.PostgresException: 42703: no existe la columna ad.adsrc

 Why is it trying to add the column adsrc? There is no such column nor table.

Any ideas?

**Comment by YohDeadfall** [comment] 2019-11-04 11:16
Duplicate of #138.

**Closed by YohDeadfall** 2019-11-04 11:16 UTC

**Comment by Rumpelstinsk** [comment] 2019-11-04 11:29
Thanks for the response @YohDeadfall. I just review the link you provied me, but I'm still confused. It saids, that one of the incompatibilities is `Remove obsolete pg_attrdef.adsrc`, and recommends using `pg_dumpall` or `pg_upgrade` to migrate data from previous version. 

In my case, i'm not migrating from previous version. I installed directly version 12 some weeks ago. Also, the publish date for EntityFRamework6.Npgsql nugget, is greater to the release date of postgreSQL 12, so it seems to be updated.

However, if, as you said, I have to set additional settings on `<provider>..</provider>` section of the app.config, could you please provide me a link with the info.

Thanks again.
