### ISSUE TITLE
Entity Data Model Wizard doesn't generate model and Close

### ISSUE THREAD

**Issue by Rigovera** [npgsql/EntityFramework6.Npgsql#63] opened 2017-01-14 18:45 UTC
visual studio 2015 sp3// postgres 9.6// npgsql 3.1.1 // EntityFramework6.Npgsql 3.1.1// .Net framework version 4.6.1

As I read in other post. I was unable to create the model from an existing database. The wizard closes after selecting the database. So I can not choose the tables or generate the model.

**Comment by Ivutar** [comment] 2017-02-08 10:02
The same. I was trying to get the edmx model as described below:
# First try

Install https://marketplace.visualstudio.com/items?itemName=RojanskyS.NpgsqlPostgreSQLIntegration extension for vs2015 Update3

Add via Nuget: Npgsql 3.2.0 + EntityFramework6.Npgsql 3.1.1 + EntityFramework 6.1.3

Try to add the new model via wizard (EF designer from database)
![image](https://cloud.githubusercontent.com/assets/1793147/22731490/4cd1b4b6-ee04-11e6-9860-906d98a92cd5.png)

**And this silently closes after pressing "Next >"**

# Second try

Install npgsql-3.2.0.msi (I know what recommended to use Npgsql.vsix and do NOT install npgsql.dll into GAC but it not work for me)

run EdmGen.exe util and **get the next error**:

![image](https://cloud.githubusercontent.com/assets/1793147/22731964/f7ba134a-ee05-11e6-85c4-6f650bbafd29.png)

After some investigations I found of hard coded string constants in Npgsql.dll:

https://github.com/npgsql/npgsql/blob/dev/src/Npgsql/NpgsqlFactory.cs

![image](https://cloud.githubusercontent.com/assets/1793147/22732103/646a9f64-ee06-11e6-8232-d1c930a78710.png)

Can be this error caused hardcoded reference to EntityFramework**5** ?

**Comment by roji** [comment] 2017-02-10 13:53
Closing as a duplicate of #1427.

In general the best way forward is to try to install the 3.2.0 VSIX on a totally clean machine, without a prior MSI installation or anything in the GAC or in any config file. If the bug still reproduces there, please post the full project (csproj etc.), VS details, etc.

**Closed by roji** 2017-02-10 13:53 UTC
