### ISSUE TITLE
Npgsql 3.0.7 in .NET 4.0: the package does not contain any assembly references or content files that are compatible with the framework

### ISSUE THREAD

**Issue by tiancai4652** [npgsql/EntityFramework6.Npgsql#142] opened 2020-01-10 02:09 UTC
my app is .net framework 4.0，i try to nuget EntityFramework6.Npgsql  3.0.7 for Npgsql  has no dependence, but it failde, then i try EntityFramework6.Npgsql  from 3.0.7 to 3.0.0, none succeed still,
they show same error:

**_"The package "Npgsql 3.0.7" could not be installed.You are trying to install this package into a project that targets ".NETFramework,Version=v4.0 ",
 but the package does not contain any assembly references or content files that are compatible with the framework.For more information,  contact the package author."_**

could you help me with this?

**Comment by YohDeadfall** [comment] 2020-01-10 07:57
Closing as duplicate of npgsql/npgsql#2786.

**Closed by YohDeadfall** 2020-01-10 07:57 UTC
